package nl.topicus.eduarte.dao.helpers;

import nl.topicus.cobra.dao.helpers.BatchZoekFilterDataAccessHelper;
import nl.topicus.eduarte.entities.participatie.VerzuimTaakSignaalDefinitieEnEventConfiguratieKoppel;
import nl.topicus.eduarte.zoekfilters.VerzuimTaakSignaalDefinitieEnEventConfiguratieKoppelZoekFilter;

public interface VerzuimTaakSignaalDefinitieEnEventConfiguratieKoppelDataAccessHelper
		extends
		BatchZoekFilterDataAccessHelper<VerzuimTaakSignaalDefinitieEnEventConfiguratieKoppel, VerzuimTaakSignaalDefinitieEnEventConfiguratieKoppelZoekFilter>
{

}